import pandas as pd


# ============================================================
# BASIC NUMERICAL ANALYSIS
# ============================================================

def calculate_sum(df, column):
    """
    Calculate the total/sum of a numerical column.
    """

    if column not in df.columns:
        raise ValueError(
            f"Column '{column}' does not exist."
        )

    return df[column].sum()


def calculate_average(df, column):
    """
    Calculate the average/mean of a numerical column.
    """

    if column not in df.columns:
        raise ValueError(
            f"Column '{column}' does not exist."
        )

    return df[column].mean()


def calculate_minimum(df, column):
    """
    Calculate the minimum value of a numerical column.
    """

    if column not in df.columns:
        raise ValueError(
            f"Column '{column}' does not exist."
        )

    return df[column].min()


def calculate_maximum(df, column):
    """
    Calculate the maximum value of a numerical column.
    """

    if column not in df.columns:
        raise ValueError(
            f"Column '{column}' does not exist."
        )

    return df[column].max()


# ============================================================
# GROUPED ANALYSIS
# ============================================================

def sum_by_group(df, group_column, value_column):
    """
    Calculate the sum of a numerical column
    grouped by another column.
    """

    if group_column not in df.columns:
        raise ValueError(
            f"Group column '{group_column}' does not exist."
        )

    if value_column not in df.columns:
        raise ValueError(
            f"Value column '{value_column}' does not exist."
        )

    result = (
        df.groupby(group_column)[value_column]
        .sum()
        .reset_index()
    )

    result = result.sort_values(
        by=value_column,
        ascending=False
    )

    return result


def average_by_group(df, group_column, value_column):
    """
    Calculate the average of a numerical column
    grouped by another column.
    """

    if group_column not in df.columns:
        raise ValueError(
            f"Group column '{group_column}' does not exist."
        )

    if value_column not in df.columns:
        raise ValueError(
            f"Value column '{value_column}' does not exist."
        )

    result = (
        df.groupby(group_column)[value_column]
        .mean()
        .reset_index()
    )

    result = result.sort_values(
        by=value_column,
        ascending=False
    )

    return result


def count_by_group(df, group_column):
    """
    Count the number of records/orders
    in each group.
    """

    if group_column not in df.columns:
        raise ValueError(
            f"Group column '{group_column}' does not exist."
        )

    result = (
        df.groupby(group_column)
        .size()
        .reset_index(name="Count")
    )

    result = result.sort_values(
        by="Count",
        ascending=False
    )

    return result


# ============================================================
# HIGHEST GROUP
# ============================================================

def highest_group(df, group_column, value_column):
    """
    Find the group with the highest total value.
    """

    grouped = sum_by_group(
        df,
        group_column,
        value_column
    )

    highest_row = grouped.iloc[0]

    return {
        "group": highest_row[group_column],
        "value": highest_row[value_column],
        "full_result": grouped
    }


# ============================================================
# LOWEST GROUP
# ============================================================

def lowest_group(df, group_column, value_column):
    """
    Find the group with the lowest total value.
    """

    grouped = sum_by_group(
        df,
        group_column,
        value_column
    )

    lowest_row = grouped.iloc[-1]

    return {
        "group": lowest_row[group_column],
        "value": lowest_row[value_column],
        "full_result": grouped
    }


# ============================================================
# EXECUTE GEMINI ANALYSIS PLAN
# ============================================================

def execute_analysis_plan(df, plan):
    """
    Execute the structured analysis plan generated by Gemini.

    IMPORTANT:
    Gemini decides WHAT the user wants.
    Pandas performs the ACTUAL calculation.
    """

    operation = plan.get("operation")
    group_column = plan.get("group_column")
    value_column = plan.get("value_column")

    # --------------------------------------------------------
    # SUM
    # --------------------------------------------------------

    if operation == "sum":

        value = calculate_sum(
            df,
            value_column
        )

        return {
            "type": "scalar",
            "operation": operation,
            "value_column": value_column,
            "value": value
        }

    # --------------------------------------------------------
    # AVERAGE
    # --------------------------------------------------------

    elif operation == "average":

        value = calculate_average(
            df,
            value_column
        )

        return {
            "type": "scalar",
            "operation": operation,
            "value_column": value_column,
            "value": value
        }

    # --------------------------------------------------------
    # MINIMUM
    # --------------------------------------------------------

    elif operation == "minimum":

        value = calculate_minimum(
            df,
            value_column
        )

        return {
            "type": "scalar",
            "operation": operation,
            "value_column": value_column,
            "value": value
        }

    # --------------------------------------------------------
    # MAXIMUM
    # --------------------------------------------------------

    elif operation == "maximum":

        value = calculate_maximum(
            df,
            value_column
        )

        return {
            "type": "scalar",
            "operation": operation,
            "value_column": value_column,
            "value": value
        }

    # --------------------------------------------------------
    # SUM BY GROUP
    # --------------------------------------------------------

    elif operation == "sum_by_group":

        result = sum_by_group(
            df,
            group_column,
            value_column
        )

        return {
            "type": "table",
            "operation": operation,
            "group_column": group_column,
            "value_column": value_column,
            "result": result
        }

    # --------------------------------------------------------
    # AVERAGE BY GROUP
    # --------------------------------------------------------

    elif operation == "average_by_group":

        result = average_by_group(
            df,
            group_column,
            value_column
        )

        return {
            "type": "table",
            "operation": operation,
            "group_column": group_column,
            "value_column": value_column,
            "result": result
        }

    # --------------------------------------------------------
    # COUNT BY GROUP
    # --------------------------------------------------------

    elif operation == "count_by_group":

        result = count_by_group(
            df,
            group_column
        )

        return {
            "type": "table",
            "operation": operation,
            "group_column": group_column,
            "value_column": None,
            "result": result
        }

    # --------------------------------------------------------
    # HIGHEST GROUP
    # --------------------------------------------------------

    elif operation == "highest_group":

        result = highest_group(
            df,
            group_column,
            value_column
        )

        return {
            "type": "highest_group",
            "operation": operation,
            "group_column": group_column,
            "value_column": value_column,
            "group": result["group"],
            "value": result["value"],
            "full_result": result["full_result"]
        }

    # --------------------------------------------------------
    # LOWEST GROUP
    # --------------------------------------------------------

    elif operation == "lowest_group":

        result = lowest_group(
            df,
            group_column,
            value_column
        )

        return {
            "type": "lowest_group",
            "operation": operation,
            "group_column": group_column,
            "value_column": value_column,
            "group": result["group"],
            "value": result["value"],
            "full_result": result["full_result"]
        }

    # --------------------------------------------------------
    # INVALID OPERATION
    # --------------------------------------------------------

    else:

        raise ValueError(
            f"Unsupported analysis operation: {operation}"
        )